name: flutter_nimplayer
description: A Flutter plugin for netease yunxin vod player. (网易云信点播播放器 SDK)
version: 0.1.0
repository: https://github.com/aJIEw/flutter_nimplayer

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.shimi.flutter_nimplayer
        pluginClass: FlutterNimplayerPlugin
      ios:
        pluginClass: FlutterNimplayerPlugin
